from TomeRater import *

Tome_Rater = TomeRater()

#Create some books:
book1 = Tome_Rater.create_book("Society of Mind", 12345678)
novel1 = Tome_Rater.create_novel("Alice In Wonderland", "Lewis Carroll", 12345)
print("\n")
novel1.set_isbn(9781536831139)
Believers_Authority = Tome_Rater.create_book("The Believer's Authority", 9876456486754)
Total_Victory = Tome_Rater.create_book("Total Victory in Jesus", 9876440895754)
Jesus_Name = Tome_Rater.create_book("In the Name of Jesus", 9886423486210)
Purple_Book = Tome_Rater.create_book("""The Purple Book""", 9780310936008)
Gods_Generals = Tome_Rater.create_book("""God's Generals - The Revivalist""", 9781603740258)

nonfiction1 = Tome_Rater.create_non_fiction("Automate the Boring Stuff", "Python", "beginner", 1929452)
nonfiction2 = Tome_Rater.create_non_fiction("Computing Machinery and Intelligence", "AI", "advanced", 11111938)
C_language = Tome_Rater.create_non_fiction("THE C PROGRAMMING LANGUAGE", "Programming", " Intermediate", 9780131103627)
C_plus_plus_language = Tome_Rater.create_non_fiction("C++ Primer", "Programming", "Beginners", 9780321714114)
iPhone_Game_Dev = Tome_Rater.create_non_fiction("iPhone Game Development", "Programming", "Intermediate", 9780596159856)
Perl  = Tome_Rater.create_non_fiction("Perl FOR DUMMIES", "Programming", "Beginners", "9780764537509")
novel2 = Tome_Rater.create_novel("The Diamond Age", "Neal Stephenson", 10101010)
novel3 = Tome_Rater.create_novel("There Will Come Soft Rains", "Ray Bradbury", 10001000)
Be_Quiet = Tome_Rater.create_novel("BE QUIET, MIKE", "Leslie Patricelli", 9780763644772)
Tower = Tome_Rater.create_novel("The Tower", "Jonathan Linton", 9780689834677)
Bat_Brothers = Tome_Rater.create_novel("BROTHERS AT BAT", "Audery Vernick", 9780547385570)
Sky_High = Tome_Rater.create_novel("Sky High", "Marissa Moss", 9781582462806)

#Create users:
Tome_Rater.add_user("Alan Turing", "alan@turing.com")
Tome_Rater.add_user("David Marr", "david@computation.org")
Tome_Rater.add_user("Enoch Olowookere", "enoch.olowo@gmail.com", [Believers_Authority, Total_Victory, Jesus_Name])
Tome_Rater.add_user("Owolabi Olowookere", "seun.olowo@silabs.com")
Tome_Rater.add_user("Rebecca Olowookere", "bexenabry06@gmail.com")

#Add a user with three books already read:
Tome_Rater.add_user("Marvin Minsky", "marvin@mit.edu", user_books=[book1, novel1, nonfiction1])

#Add books to a user one by one, with ratings:
Tome_Rater.add_book_to_user(book1, "alan@turing.com", 1)
Tome_Rater.add_book_to_user(novel1, "alan@turing.com", 3)
Tome_Rater.add_book_to_user(nonfiction1, "alan@turing.com", 3)
Tome_Rater.add_book_to_user(nonfiction2, "alan@turing.com", 4)
Tome_Rater.add_book_to_user(novel3, "alan@turing.com", 1)

#Add books to a user one by one, with ratings and prices in Dollars:
Tome_Rater.add_book_to_user(Jesus_Name, "bexenabry06@gmail.com", 4, 12.50)
Tome_Rater.add_book_to_user(Purple_Book, "bexenabry06@gmail.com", 3, 15.79)
Tome_Rater.add_book_to_user(Believers_Authority, "bexenabry06@gmail.com", 4, 12.50)
Tome_Rater.add_book_to_user(Total_Victory, "bexenabry06@gmail.com", 4, 5.78)
Tome_Rater.add_book_to_user(Believers_Authority, "seun.olowo@silabs.com", 2, 12.75)
Tome_Rater.add_book_to_user(Purple_Book, "seun.olowo@silabs.com", 1, 20.00)
Tome_Rater.add_book_to_user(Gods_Generals, "seun.olowo@silabs.com", 3, 25.55)
Tome_Rater.add_book_to_user(C_language, "seun.olowo@silabs.com", 3, 35.50)
Tome_Rater.add_book_to_user(C_plus_plus_language, "seun.olowo@silabs.com", 3, 19.95)
Tome_Rater.add_book_to_user(iPhone_Game_Dev, "seun.olowo@silabs.com", 2, 7.99)
Tome_Rater.add_book_to_user(Perl, "seun.olowo@silabs.com", 1, 13.99)
Tome_Rater.add_book_to_user(Be_Quiet, "seun.olowo@silabs.com", 1, 1.75)
Tome_Rater.add_book_to_user(Tower, "seun.olowo@silabs.com", 2, 0.85)
Tome_Rater.add_book_to_user(Bat_Brothers, "seun.olowo@silabs.com", 3, 1.25)
Tome_Rater.add_book_to_user(Sky_High, "seun.olowo@silabs.com", 4, 2.25)
Tome_Rater.add_book_to_user(Sky_High, "seun.olowo@silabs.com", 4, 2.25)
Tome_Rater.add_book_to_user(Purple_Book, "enoch.olowo@gmail.com", 4, 12.25)
Tome_Rater.add_book_to_user(Purple_Book, "enoch.olowo@gmail.com", 4, 12.75)
Tome_Rater.add_book_to_user(Believers_Authority, "enoch.olowo@gmail.com", 4, 11.00)
Tome_Rater.add_book_to_user(Total_Victory, "enoch.olowo@gmail.com", 4, 4.00)
Tome_Rater.add_book_to_user(Believers_Authority, "enoch.olowo@gmail.com", 4, 13.00)
Tome_Rater.add_book_to_user(Purple_Book, "enoch.olowo@gmail.com", 4, 12.65)
Tome_Rater.add_book_to_user(Gods_Generals, "enoch.olowo@gmail.com", 4, 22.95)
Tome_Rater.add_book_to_user(C_language, "enoch.olowo@gmail.com",4, 35.95)

Tome_Rater.add_book_to_user(novel2, "marvin@mit.edu", 2)
Tome_Rater.add_book_to_user(novel3, "marvin@mit.edu", 2)
Tome_Rater.add_book_to_user(novel3, "david@computation.org", 4)

print("\n")
#Uncomment these to test your functions:
print("My Tome Rater Catalog:\n")
Tome_Rater.print_catalog()
print("\n")
print("\n")
print("All users in Tome_Rater Library:")
print("\n")
Tome_Rater.print_users()
print("\n")
print("\n")
My_Name_Seun = Tome_Rater.create_book("My Name is Seun", 9876456486754)
print("\n")
print("Most positive user:")
print(Tome_Rater.most_positive_user(), "\n\n")
print("Highest rated book:")
print(Tome_Rater.highest_rated_book(), "\n\n")
print("Most read book:")
print(Tome_Rater.most_read_book(), "\n\n")
print("Most Prolific Reader:")
print(Tome_Rater.most_prolific_reader(), "\n\n")
Tome_Rater.get_n_most_read_books(12)
print("\n")
Tome_Rater.get_n_most_prolific_readers(5)
print("\n")
Tome_Rater.get_n_most_expensive_books(7)
print("\n")
print(Tome_Rater.get_worth_of_user("seun.olowo@silabs.com"), "\n\n")
print(Tome_Rater.get_worth_of_user("bexenabry06@gmail.com"), "\n\n")
print(Tome_Rater.get_worth_of_user("enoch.olowo@gmail.com"), "\n\n")